spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smt?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

hibernate:
  dialect: org.hibernate.dialect.MySQLDialect
  show-sql: true
  format-sql: false
  ddl-auto: none

smt:
  app:
    jwtSecret: smtSecretKey
    jwtExpirationMs: 86400000
